# -*- coding: utf-8 -*-
"""fyolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3kYBR5mbi7D6ThFPVmDduGa8SSfISY_
"""


!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

import os
os.environ["KAGGLE_USERNAME"] = "pehdinghaopauline"
os.environ["KAGGLE_KEY"] = "KGAT_e3cd65a71b97e0605d6ebad8739d6b2b"

!pip install kaggle

!kaggle datasets list -s widerface

!kaggle datasets download -d lylmsc/wider-face-for-yolo-training -p /content
!unzip -q /content/wider-face-for-yolo-training.zip -d /content
!ls /content

data_yaml = """
path: /content
train: images
val: images

names:
  0: face
"""

with open("/content/data.yaml", "w") as f:
    f.write(data_yaml)

!cat /content/data.yaml

!ls /content
!ls /content/images | head
!ls /content/labels | head

from ultralytics import YOLO

# load model
model = YOLO("yolo11n.pt")

# start training
model.train(
    data="/content/data.yaml",
    epochs=10,
    imgsz=640,
    batch=16
)

!ls /content/runs/detect/train/weights

from ultralytics import YOLO
import glob, random

# load your trained model
model = YOLO("/content/runs/detect/train/weights/best.pt")

# pick 5 random images
imgs = random.sample(glob.glob("/content/images/*.jpg"), 5)

# run detection
model.predict(source=imgs, conf=0.25, save=True)

!ls /content/runs/detect/predict

from IPython.display import Image, display
import glob

for img in glob.glob("/content/runs/detect/predict/*.jpg"):
    display(Image(filename=img))

from google.colab import files
files.download("/content/runs/detect/train/weights/best.pt")

model.predict(source="/content/people pic.jpg", conf=0.5, save=True)

!ls /content/runs/detect/predict

from IPython.display import Image, display

display(Image("/content/runs/detect/predict/people pic.jpg"))

import glob, os

runs = sorted(glob.glob("/content/runs/detect/train*"), key=os.path.getmtime)
print("Latest run:", runs[-1])
run_dir = runs[-1]

import os, glob

run_dir = "/content/runs/detect/train2"   # from your print
print("Run dir:", run_dir)
print("Files:", os.listdir(run_dir))

!find /content/runs/detect -maxdepth 3 -name "results.csv" -print

import pandas as pd

run_dir = "/content/runs/detect/train"   # <-- important
csv_path = f"{run_dir}/results.csv"

df = pd.read_csv(csv_path)
df.head()

import matplotlib.pyplot as plt

# show column names so you know what exists
print(df.columns)

x = df["epoch"] if "epoch" in df.columns else range(len(df))

# pick common ultralytics columns (only plot if they exist)
to_plot = [
    "train/box_loss", "train/cls_loss", "train/dfl_loss",
    "val/box_loss", "val/cls_loss", "val/dfl_loss",
    "metrics/precision(B)", "metrics/recall(B)",
    "metrics/mAP50(B)", "metrics/mAP50-95(B)"
]

for col in to_plot:
    if col in df.columns:
        plt.figure()
        plt.plot(x, df[col])
        plt.xlabel("epoch")
        plt.ylabel(col)
        plt.title(col)
        plt.show()



model.train(data="/content/data.yaml", epochs=5, imgsz=640, batch=16)

!ls /content/runs/detect

import glob, os

candidates = glob.glob("/content/runs/detect/train*/results.csv")
candidates = sorted(candidates, key=os.path.getmtime)

print("Found these results.csv files:")
for p in candidates:
    print(p, " | modified:", os.path.getmtime(p))

print("\nLatest:", candidates[-1] if candidates else "NONE")

import pandas as pd

csv_path = "/content/runs/detect/train3/results.csv"
df = pd.read_csv(csv_path)

print("Rows loaded:", len(df))
print(df[['epoch','train/box_loss','metrics/mAP50(B)']])

import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))

# TRAINING LOSS
plt.subplot(2,2,1)
plt.plot(df['epoch'], df['train/box_loss'], label='box_loss')
plt.plot(df['epoch'], df['train/cls_loss'], label='cls_loss')
plt.plot(df['epoch'], df['train/dfl_loss'], label='dfl_loss')
plt.title("Training Loss")
plt.xlabel("Epoch")
plt.legend()

# 2️PRECISION vs RECALL
plt.subplot(2,2,2)
plt.plot(df['epoch'], df['metrics/precision(B)'], label='Precision')
plt.plot(df['epoch'], df['metrics/recall(B)'], label='Recall')
plt.title("Precision vs Recall")
plt.xlabel("Epoch")
plt.legend()

# mAP PERFORMANCE
plt.subplot(2,2,3)
plt.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP50')
plt.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP50-95')
plt.title("mAP Performance")
plt.xlabel("Epoch")
plt.legend()

# VALIDATION LOSS
plt.subplot(2,2,4)
plt.plot(df['epoch'], df['val/box_loss'], label='val_box_loss')
plt.plot(df['epoch'], df['val/cls_loss'], label='val_cls_loss')
plt.plot(df['epoch'], df['val/dfl_loss'], label='val_dfl_loss')
plt.title("Validation Loss")
plt.xlabel("Epoch")
plt.legend()

plt.tight_layout()
plt.show()

!ls /content/runs/detect/train/weights

!pip -q install ultralytics

from ultralytics import YOLO
model = YOLO("/content/runs/detect/train3/weights/best.pt")
